from .Admin import create_adminler_table
from .Student import create_ogrenciler_table,ogrenci_guncelle,ogrenci_sil,tum_ogrencileri_getir,ogrenci_ekle
from .Teacher import create_ogretmenler_table,ogretmen_sil,ogretmen_guncelle,tum_ogretmenleri_getir,ogretmen_ekle
from .Class import create_dersler_table,ders_guncelle,ders_sil,tum_dersleri_getir,ders_ekle
from .ManyToMany import create_ogretmen_ders_table,create_ogretmen_ogrenci_table
from .ModelBuilder import ogretmene_ders_sil,ogretmene_ders_ata,ogretmenin_derslerini_getir
from .ModelBuilder import ogretmenin_ogrencilerini_getir,ogretmene_ogrenci_ata,ogretmene_ogrencilerini_sil
from .ModelBuilder import ogrenci_ders_ata,ogrencinin_ders_sil,ogrencinin_derslerini_getir