from .getStudents import ogrencileri_listele_gui
from .createStudent import ogrenci_ekleme_sayfasi
from .assignClassToStudent import ders_ekle_ogrenci
from .assignTeacherToStudent import ogretmen_ekle_ogrenci