from .TeacherCourse import ogretmene_ders_ata,ogretmene_ders_sil,ogretmenin_derslerini_getir
from .TeacherStudent import ogretmene_ogrenci_ata,ogretmene_ogrencilerini_sil,ogretmenin_ogrencilerini_getir
#ogretmene_ait_tum_dersleri_sil